version: '3.1'
services:
  tomcat:
    container_name: tomcat
    build:
      context: ./docker/tomcat/
    ports:
      - 9000:8080
    volumes:
      - ./target/war-for-migrate:/usr/local/tomcat/webapps-javaee
    environment:
      TZ: Asia/Tehran
      JDBC_URL: jdbc:mysql://mysql:3306/employee_db
      JDBC_USER: root
      JDBC_PASS: 123456
    links:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mySqlContainer
    ports:
      - 3307:3306
    environment:
      TZ: Asia/Tehran
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: employee_db
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/mysql:/var/lib/mysql
